version: '3.8'
services:
  snu-dev-db:   #Container Name
    image: postgres:13
    ports :
      - 5434:5432
    environment:  #Environment Variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks: #To be on the given network
      - sn-universities
networks :
  sn-universities: